### ISSUE TITLE
Doom2 instantly crahes on game start (divide by 0)

### ISSUE THREAD

**Issue by ariahiro64** [thekovic/ClassicDoomN64#4]
steps to reproduce:
download and install libdragons preview branch
boot the rom (happens on both hardware and emulator)
choose new game
choose difficulty (any)
as soon as doomguy raises his pistol the game crashes
![Screenshot_20240722_185623](https://github.com/user-attachments/assets/7d7a1ec7-c57d-4046-b8bd-073e53e2e75a)
![Screenshot_20240722_185636](https://github.com/user-attachments/assets/80ba4ee7-aee7-44c2-ba17-fc2254a6fc4c)
![Screenshot_20240722_185647](https://github.com/user-attachments/assets/88230da1-75cd-47e8-abbd-ff0c205e03ec)

**Comment by thekovic** [comment]
Fixed in https://github.com/thekovic/ClassicDoomN64/commit/98472f16187f46b40255104bca5f7b10e23ea05b
